version: '3'
services:
  waardepapieren-service:
    volumes:
    - ./waardepapieren-service/system-test/certs:/certs:ro
    - ./waardepapieren-service/configuration/:/app/configuration:ro
    build: waardepapieren-service/.
    links:
      - mock-nlx
    ports:
      - 3232:3232
      - 3233:3233
    environment:
    - WAARDEPAPIEREN_CONFIG=/app/configuration/waardepapieren-config-compose.json
  clerk-frontend:
    build: clerk-frontend/
    links:
      - waardepapieren-service
    ports:
    - 443:443
    - 8880:8880
    healthcheck:
      test: service nginx status
    volumes:
    - ./clerk-frontend/nginx/certs:/etc/nginx/certs:ro
  mock-nlx:
    image: nlxio/outway:latest
    volumes:
      - ./waardepapieren-service/system-test/certs:/certs:ro
    environment:
      - DIRECTORY_INSPECTION_ADDRESS=directory-inspection-api.demo.nlx.io:443
      - TLS_NLX_ROOT_CERT=/certs/root.crt
      - TLS_ORG_CERT=/certs/org.crt
      - TLS_ORG_KEY=/certs/org.key
      - DISABLE_LOGDB=1
    ports:
      - 80:80
